"""Bake an SVG glyph into the launcher icon's 108-unit viewport.

Takes SVG path data in any viewport, scales and centres it so every painted pixel lands
inside the circle an adaptive-icon mask can crop to, and writes the drawable with plain
108-unit coordinates. Nothing is transformed at runtime.

    python3 scripts/fit_icon.py body.svgfrag app/src/main/res/drawable/ic_launcher_foreground.xml

Input is either an SVG file or a fragment of one or more <path d="..."> elements.
"""
import math
import re
import sys

from svg_path import bounds, flatten, transform

# The mask can crop to a 72dp circle on a 108dp canvas, so radius 36 is the hard edge.
# 34 leaves a margin for rounding and for launchers that crop a shade tighter.
SAFE_RADIUS = 34.0
# No outline. This glyph's limbs are thin once it is scaled into the icon, and even a
# 2-unit mint outline closes them up at launcher size; the plain white silhouette reads
# far better. Set OUTLINE and STROKE to bring one back.
STROKE = 0.0
FILL = "#FFFFFF"
OUTLINE = None

TEMPLATE = """<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!--
      Generated by scripts/fit_icon.py. Edit the source glyph and re-run rather than
      hand-tuning the coordinates below.
{note}
    -->
{paths}
</vector>
"""

PATH = """    <path
        android:fillColor="{fill}"
        android:strokeColor="{outline}"
        android:strokeWidth="{stroke:g}"
        android:strokeLineJoin="round"
        android:strokeLineCap="round"
        android:pathData="{d}" />"""

PLAIN_PATH = """    <path
        android:fillColor="{fill}"
        android:pathData="{d}" />"""


def fit(paths, safe_radius=None, stroke=None):
    """Scale and centre so the outermost painted pixel sits on `safe_radius`."""
    # Read the module globals at call time so a caller can retune them.
    safe_radius = SAFE_RADIUS if safe_radius is None else safe_radius
    stroke = STROKE if stroke is None else stroke
    x0, y0, x1, y1 = bounds(paths)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    pts = [p for d in paths for sub in flatten(d) for p in sub]
    # Distance from the glyph's own centre, not the bounding box: a bounding box would
    # over-shrink a tall figure whose corners hold nothing.
    max_r = max(math.hypot(px - cx, py - cy) for px, py in pts)
    scale = (safe_radius - stroke / 2) / max_r
    return [transform(d, scale, 54 - cx * scale, 54 - cy * scale) for d in paths], scale


def main(src, dst, note=""):
    text = open(src, encoding="utf-8").read()
    paths = re.findall(r'\sd="([^"]+)"', text) or [text.strip()]
    fitted, scale = fit(paths)
    body = "\n".join(
        (PATH if OUTLINE and STROKE else PLAIN_PATH).format(
            fill=FILL, outline=OUTLINE, stroke=STROKE, d=d
        )
        for d in fitted
    )
    open(dst, "w", encoding="utf-8").write(
        TEMPLATE.format(paths=body, note=("\n" + note if note else ""))
    )
    x0, y0, x1, y1 = bounds(fitted)
    print(f"{len(paths)} paths, scale {scale:.4f}, bounds x {x0:.1f}..{x1:.1f} y {y0:.1f}..{y1:.1f}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else "")
